# Generated by Django 4.2 on 2023-05-03 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_category', models.CharField(choices=[('1', 'DATA Slot1'), ('2', 'DATA Slot2'), ('3', 'DATA Slot3'), ('4', 'DATA Slot4'), ('5', 'DATA Slot5'), ('1', 'VOIC Slot1'), ('2', 'VOIC Slot2'), ('3', 'VOIC Slot3')], max_length=1)),
                ('slot_from', models.DateTimeField()),
                ('slot_to', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
