# Generated by Django 4.2 on 2023-05-03 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ENGKalenderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot_to',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot_category',
            field=models.CharField(choices=[('1 DA', 'DATA Slot1'), ('2 DA', 'DATA Slot2'), ('3 DA', 'DATA Slot3'), ('4 DA', 'DATA Slot4'), ('5 DA', 'DATA Slot5'), ('1 VO', 'VOIC Slot1'), ('2 VO', 'VOIC Slot2'), ('3 VO', 'VOIC Slot3')], max_length=4),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_from', models.DateTimeField()),
                ('slot_to', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENGKalenderApp.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
