# Generated by Django 4.2 on 2023-05-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENGKalenderApp', '0002_remove_booking_slot_from_remove_booking_slot_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='slot_category',
            new_name='category',
        ),
    ]
