# Generated by Django 4.2 on 2023-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGKalenderApp', '0003_rename_slot_category_booking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('1', 'DATA Slot1'), ('2', 'DATA Slot2'), ('3', 'DATA Slot3'), ('4', 'DATA Slot4'), ('5', 'DATA Slot5'), ('6', 'VOIC Slot1'), ('7', 'VOIC Slot2'), ('8', 'VOIC Slot3')], max_length=4),
        ),
    ]
