# Generated by Django 4.2 on 2023-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGKalenderApp', '0004_alter_booking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('one', 'DATA Slot1'), ('two', 'DATA Slot2'), ('thr', 'DATA Slot3'), ('fou', 'DATA Slot4'), ('fiv', 'DATA Slot5'), ('six', 'VOIC Slot1'), ('sev', 'VOIC Slot2'), ('eig', 'VOIC Slot3')], max_length=4),
        ),
    ]
