# Generated by Django 4.2 on 2023-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGKalenderApp', '0005_alter_booking_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('DATA', 'DATA Slot'), ('VOIC', 'VOIC Slot')], max_length=4),
        ),
    ]
