# Generated by Django 4.2 on 2023-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENGKalenderApp', '0006_booking_slot_alter_booking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('DA1', 'DATA Slot 1'), ('DA2', 'DATA Slot 2'), ('DA3', 'DATA Slot 3'), ('DA4', 'DATA Slot 4'), ('DA5', 'DATA Slot 5'), ('VO1', 'VOIC Slot 1'), ('VO2', 'VOIC Slot 2'), ('VO3', 'VOIC Slot 3')], max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
